parallel-jobs = 1

[MaterialYou-rvx]
app-name = "og-material-you"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "rvx"
riplib = false
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'MaterialYou' 'Change version code'"
excluded-patches = "'Theme' 'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube'"
remove-rv-integrations-checks = false

[Darker-MaterialYou-rvx]
app-name = "da-rker-matterialyou"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "rvx"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@color/m3_ref_palette_dynamic_neutral_variant6 -OlightThemeBackgroundColor=@color/m3_ref_palette_dynamic_neutral_variant98"
riplib = false
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'MaterialYou' 'Change version code'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube'"
remove-rv-integrations-checks = false

[Black-rvx]
app-name = "og-black"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "rvx"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black"
riplib = false
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Change version code'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube'"
remove-rv-integrations-checks = false

[Dark-rvx]
app-name = "og-dark"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "rvx"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#FF0F0F0F"
riplib = false
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Change version code'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube'"
remove-rv-integrations-checks = false

[Grey-rvx]
app-name = "grey"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "rvx"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#FF212121"
riplib = false
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Change version code'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube'"
remove-rv-integrations-checks = false

[MaterialYou-rv]
app-name = "materiialyou"
cli-source = "ReVanced/revanced-cli"
build-mode = "apk"
rv-brand = "rv"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/system_neutral1_900 -OlightThemeBackgroundColor=@android:color/system_neutral1_50"
riplib = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Change version code'"
excluded-patches = "'Change header' 'Custom branding'"

[Darker-MaterialYou-rv]
app-name = "d-arker-materiiialyou"
cli-source = "ReVanced/revanced-cli"
build-mode = "apk"
rv-brand = "rv"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@color/m3_ref_palette_dynamic_neutral_variant6 -OlightThemeBackgroundColor=@color/m3_ref_palette_dynamic_neutral_variant98"
riplib = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Change version code'"
excluded-patches = "'Change header' 'Custom branding'"

[Black-rv]
app-name = "blaack"
cli-source = "ReVanced/revanced-cli"
build-mode = "apk"
rv-brand = "rv"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black"
riplib = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Change version code'"
excluded-patches = "'Change header' 'Custom branding'"

[Dark-rv]
app-name = "daark"
cli-source = "ReVanced/revanced-cli"
build-mode = "apk"
rv-brand = "rv"
riplib = false
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#FF0F0F0F"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Change version code'"
excluded-patches = "'Change header' 'Custom branding'"

[Grey-rv]
app-name = "grrey"
cli-source = "ReVanced/revanced-cli"
build-mode = "apk"
rv-brand = "rv"
riplib = false
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#FF212121"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Change version code'"
excluded-patches = "'Change header' 'Custom branding'"

[MaterialYou-morphe]
app-name = "materiiaalyou"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
build-mode = "apk"
rv-brand = "morphe"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/system_neutral1_900 -OlightThemeBackgroundColor=@android:color/system_neutral1_50"
riplib = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Change version code'"
excluded-patches = "'Change header' 'Custom branding'"

[Darker-MaterialYou-morphe]
app-name = "d-arker-materiiiaalyou"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
build-mode = "apk"
rv-brand = "morphe"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@color/m3_ref_palette_dynamic_neutral_variant6 -OlightThemeBackgroundColor=@color/m3_ref_palette_dynamic_neutral_variant98"
riplib = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Change version code'"
excluded-patches = "'Change header' 'Custom branding'"

[Black-morphe]
app-name = "blacck"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
build-mode = "apk"
rv-brand = "morphe"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black"
riplib = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Change version code'"
excluded-patches = "'Change header' 'Custom branding'"

[Dark-morphe]
app-name = "daarrk"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
build-mode = "apk"
rv-brand = "morphe"
riplib = false
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#FF0F0F0F"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Change version code'"
excluded-patches = "'Change header' 'Custom branding'"

[Grey-morphe]
app-name = "greey"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
build-mode = "apk"
rv-brand = "morphe"
riplib = false
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#FF212121"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Change version code'"
excluded-patches = "'Change header' 'Custom branding'"

[BlackA6-7]
enabled = false
patches-version = "dev"
remove-rv-integrations-checks = false
app-name = "bllack"
patches-source = "kitadai31/revanced-patches-android6-7"
cli-source = "inotia00/revanced-cli"
rv-brand = "rvx-a6-7"
version = "17.34.36"
riplib = false
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = ""
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube'"

[DarkA6-7]
enabled = false
patches-version = "dev"
remove-rv-integrations-checks = false
app-name = "darrk"
patches-source = "kitadai31/revanced-patches-android6-7"
cli-source = "inotia00/revanced-cli"
rv-brand = "rvx-a6-7"
version = "17.34.36"
riplib = false
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = ""
excluded-patches = "'Theme' 'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube'"
